# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: "Libo's Blog"
description: "Libo Blog"
keywords: "AR,VR,DP,Machine Learning"
url: http://next.sh
# baseurl: "/end2end"
baseurl: ""

# google_analytics: UA-52446115-1
repo: https://github.com/libos/libos.github.io
disqus_shortname: "libos"

# Author settings
author:
  name      : Libo Liu
  job       : Freelance
  bio       : "Freelance"
  thumb     : /images/author.jpg
  email     : llb0536@gmail.com
  url       : http://next.sh
  github    : http://github.com/libos
  twitter   : http://twitter.com/liberliu
  facebook  : http://facebook.com/gslipt

# navbar pages
navbar:
  - slug: about
    title: About
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]